"use client";
import React, { useState } from 'react';
import ChatInterface from '@/components/chat/ChatInterface';
import PlaygroundArea, { PlaygroundContentType } from '@/components/chat/PlaygroundArea';

export default function Home() {
  const [playgroundTitle, setPlaygroundTitle] = useState("Code Playground");
  const [playgroundContent, setPlaygroundContent] = useState("Code generated by OmniAssist will appear here. Start by interacting with the chat on the left!");
  const [playgroundContentType, setPlaygroundContentType] = useState<PlaygroundContentType>('welcome'); // Or 'code' if you want to always assume code

  const handleContentGenerated = (content: string, type: PlaygroundContentType, title: string) => {
    if (type === 'code') {
      setPlaygroundTitle(title);
      setPlaygroundContent(content);
      setPlaygroundContentType(type);
    }
    // Text and image content will appear in chat history but not update the playground
  };

  return (
    <div className="flex flex-1 overflow-hidden h-full">
      {/* Left Panel: Chat Interface */}
      <div className="w-full md:w-2/5 lg:w-1/3 flex flex-col h-full border-r bg-card overflow-hidden">
        <ChatInterface onContentGenerated={handleContentGenerated} />
      </div>

      {/* Right Panel: Playground Area */}
      <div className="hidden md:flex md:w-3/5 lg:w-2/3 flex-col h-full bg-background overflow-hidden">
        <PlaygroundArea
          title={playgroundTitle}
          content={playgroundContent}
          contentType={playgroundContentType}
        />
      </div>
    </div>
  );
}
